### PR TITLE
Updating API to Jasmine 2.1

### PR DESCRIPTION
**Pull request by Bruddles**
Fixes Issue #1. 
EDIT: Spotted a bug, working on a fix now, will update you when its done.

### CODE REVIEW

**Comment by nippur72** [comment]
ok, tell me when ready

**Comment by Bruddles** [comment]
I've fixed the issue to the best of my ability, some of it is sub optimal but it doesn't look like there's a better solution. My last commit details the changes made, but if you have any questions or suggestions please let me know.

**Comment by nippur72** [comment]
Wow, that's a lot of changes! And, shame on me, I haven't updated myself to Jasmine 2 yet. So I'll merge it for now and check the whole thing later. 

Thanks a lot, BTW!

**Comment by nippur72** [comment]
I'm giving a better look at your pull request now. You did a great job!

Among some other things, I've noticed that `pending()` was commented/disabled. So I tried to uncomment it and realized it does not work well (`expect()` is executed despite being marked as pending). 

But I noticed also that if you comment all the other specs, the `pending` works as intended, (`expect()` is not called). Do you have any clue why this happens? Do you think it's a Jasmine bug or something that has to do with Saltarelle? 

I tried also to use the v2.2.0, because there is a new `pending(reason)` (with string parameter), but there is the same behavior.

**Comment by Bruddles** [comment]
Sorry for the late reply. We noticed it wasn't working in Phantom, but it looked like it was working in Chrome, so we assumed it was a bug in Phantom. Didn't try commenting out all of the other tests though.

**Pull request merged**
